### ISSUE TITLE
False positive: DuckDuckGo Tracker Radar marks video from yandex.ru as tracker

### ISSUE THREAD

**Issue by mad-gooze** [duckduckgo/tracker-radar#293] opened 2024-11-14 18:42 UTC
Steps to reproduce:

Go to https://scale.yandex.cloud/?videoTab= in Vivaldi Browser with DuckDuckGo Tracker Radar enabled
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/df65c361-1924-4fdd-89d7-2e2300e86477">

What should happen:
Video Player should be displayed

What actually happens:
video player iframe is being blocked 
https://runtime.strm.yandex.ru/player/video/vplvxnopzpcrt6xnlmtv?from=videohub&autoplay=0&playerapi-version=11947&primary_color=FFFFFF
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/5734e7e4-d90f-4b20-9a47-9ca132244202">

Environment:

Vivaldi | 7.0.3495.14
macOS Version 14.7 

DuckDuckGo Tracker Radar also seems to block all requests to *.strm.yandex.ru and *.strm.yandex.net wich provide video manifests and segments.

**Comment by muodov** [comment] 2024-11-20 10:13
@mad-gooze thanks for reporting!
- We looked into this and [mitigated](https://github.com/duckduckgo/privacy-configuration/pull/2481) the issue in DDG apps.
- We don't have control over Vivaldi's development, so can't tell when it will be fixed there. We did [fix](https://github.com/duckduckgo/tracker-radar/pull/294) the root cause (missing entity domains), so hopefully they pull that change and it should resolve the problem.

That said, in the future I recommend to report site breakage directly in DDG products (browsers and extensions). Github issues in this repo are not monitored regularly, so things may get lost.

**Closed by muodov** 2024-11-20 10:13 UTC
